# Generated by Django 5.1.2 on 2024-11-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Cuenta', models.CharField(max_length=50, unique=True)),
                ('Contrasena', models.CharField(max_length=25)),
                ('Rol', models.IntegerField(choices=[(1, 'MESERO'), (2, 'CHEF')])),
            ],
        ),
        migrations.CreateModel(
            name='PEDIDO',
            fields=[
                ('IdPedido', models.AutoField(primary_key=True, serialize=False)),
                ('Mesa', models.IntegerField()),
                ('Platillo', models.CharField(max_length=200)),
                ('Estatus', models.IntegerField(choices=[(1, 'CREADO'), (2, 'ACEPTADO')], default=1)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('IdUsuarioRegistro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.usuario')),
            ],
        ),
    ]
