# Generated by Django 5.1.2 on 2024-11-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Estatus',
            new_name='estatus',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='FechaRegistro',
            new_name='fechaRegistro',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='IdPedido',
            new_name='idPedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='IdUsuarioRegistro',
            new_name='idUsuarioRegistro',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Mesa',
            new_name='mesa',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Platillo',
            new_name='platillo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Contrasena',
            new_name='contrasena',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Cuenta',
            new_name='cuenta',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='IdUsuario',
            new_name='idUsuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Rol',
            new_name='rol',
        ),
    ]
