# Generated by Django 5.1.2 on 2024-11-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_estatus_pedido_estatus_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('cuenta',), name='unique_cuenta'),
        ),
    ]
